import AppError from "./appError";

export const ERRORS = {
    DATABASE_READ_ERROR: 'DATABASE_READ_ERROR',
    DATABASE_WRITE_ERROR: 'DATABASE_WRITE_ERROR',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
    INVALID_ITEM_DATA: 'INVALID_ITEM_DATA',
    COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
    INVALID_COURSE_DATA: 'INVALID_COURSE_DATA',
    INVALID_SETTINGS_DATA: 'INVALID_SETTINGS_DATA',
    INVALID_ICAL_URL: 'INVALID_ICAL_URL',
    INVALID_ICAL_DATA: 'INVALID_ICAL_DATA',
    ICAL_FETCH_FAILED: 'ICAL_FETCH_FAILED',
    ICAL_PARSE_FAILED: 'ICAL_PARSE_FAILED',
    ICAL_ALREADY_EXISTS: 'ICAL_ALREADY_EXISTS',
};
export type ErrorType = typeof ERRORS[keyof typeof ERRORS];

export const STATUS_CODES = {
    OK: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
};
export type StatusCode = typeof STATUS_CODES[keyof typeof STATUS_CODES];

const HttpMap = {
    [ERRORS.DATABASE_READ_ERROR]: 500,
    [ERRORS.DATABASE_WRITE_ERROR]: 500,
    [ERRORS.USER_ALREADY_EXISTS]: 400,
    [ERRORS.INVALID_CREDENTIALS]: 401,
    [ERRORS.INVALID_PASSWORD]: 400,
    [ERRORS.ITEM_NOT_FOUND]: 404,
    [ERRORS.INVALID_ITEM_DATA]: 400,
    [ERRORS.COURSE_NOT_FOUND]: 404,
    [ERRORS.INVALID_COURSE_DATA]: 400,
    [ERRORS.INVALID_SETTINGS_DATA]: 400,
    [ERRORS.INVALID_ICAL_URL]: 400,
    [ERRORS.INVALID_ICAL_DATA]: 400,
    [ERRORS.ICAL_FETCH_FAILED]: 502,
    [ERRORS.ICAL_PARSE_FAILED]: 422,
    [ERRORS.ICAL_ALREADY_EXISTS]: 409,
};

export function getStatusCode(appError: AppError): number {
    return HttpMap[appError.errorCode] || 500;
}